# --------------------
# Metrics Cops
# --------------------
Metrics/AbcSize:
  Enabled: true
  Max: 35
Metrics/BlockLength:
  Max: 5
  IgnoredMethods:
    - context
    - describe
    - it
    - shared_examples
    - shared_examples_for
    - namespace
    - draw
    - configure
    - group
  Exclude:
    - "**/concerns/**/*.rb"
    - "**/*.rake"
    - "**/api/api/**/*.rb" # we exclude this because of large blocks required in "grape".
Metrics/ClassLength:
  Enabled: true
  Max: 200
Metrics/MethodLength:
  Enabled: true
  Max: 20

# --------------------
# Layout Cops
# --------------------
Layout/AccessModifierIndentation: # private/protected/public
  EnforcedStyle: outdent
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: no_empty_lines
Layout/FirstHashElementIndentation:
  Enabled: true
  EnforcedStyle: consistent
Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_explicit
Layout/LineLength:
  Enabled: true
  Max: 120
Layout/SpaceAroundMethodCallOperator:
  Enabled: false
Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space

# --------------------
# Style Cops
# --------------------
Style/AccessorGrouping:
  Enabled: false
Style/ArrayCoercion:
  Enabled: false
Style/BisectedAttrAccessor:
  Enabled: false
Style/CaseLikeIf:
  Enabled: false
Style/ClassAndModuleChildren:
  Exclude:
    - "**/api/api/**/*.rb"
Style/ClassVars:
  Exclude:
    - "**/api/api/**/*.rb"
Style/CollectionMethods:
  Description: "Preferred collection methods."
  Enabled: true
Style/CombinableLoops:
  Enabled: true
Style/Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false
Style/Encoding:
  Enabled: false
Style/ExplicitBlockArgument:
  Enabled: false
Style/ExponentialNotation:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Style/HashAsLastArrayItem:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashLikeCase:
  Enabled: false
Style/HashSyntax:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/KeywordParametersOrder:
  Enabled: true
Style/MethodCalledOnDoEndBlock:
  Description: "Avoid chaining a method call on a do...end block."
  Enabled: true
Style/OptionalBooleanParameter:
  Enabled: false
Style/ParenthesesAroundCondition:
  Description: "Don't use parentheses around the condition of an if/unless/while."
  Enabled: false
Style/PreferredHashMethods:
  Description: "Checks use of `has_key?` and `has_value?` Hash methods."
  EnforcedStyle: verbose
Style/RedundantAssignment:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Style/RedundantFileExtensionInRequire:
  Enabled: false
Style/RedundantRegexpCharacterClass:
  Enabled: false
Style/RedundantRegexpEscape:
  Enabled: false
Style/RedundantSelfAssignment:
  Enabled: true
Style/SingleArgumentDig:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false
Style/SoleNestedConditional:
  Enabled: true
Style/StringConcatenation:
  Enabled: false
Style/StringLiterals:
  Description: "Checks if uses of quotes match the configured preference."
  EnforcedStyle: double_quotes

# --------------------
# Lint Cops
# --------------------
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: false
Lint/DeprecatedOpenSSLConstant:
  Enabled: false
Lint/DuplicateElsifCondition:
  Enabled: false
Lint/DuplicateRequire:
  Enabled: true
Lint/DuplicateRescueException:
  Enabled: false
Lint/EmptyConditionalBody:
  Enabled: false
Lint/EmptyFile:
  Enabled: true
Lint/FloatComparison:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/MixedRegexpCaptureTypes:
  Enabled: false
Lint/OutOfRangeRegexpRef:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/SelfAssignment:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Lint/TopLevelReturnWithArgument:
  Enabled: false
Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true
Lint/UnreachableLoop:
  Enabled: false
Lint/UnusedBlockArgument: # No auto-correct for unused block arguments, but will still warn.
  AutoCorrect: false
Lint/UnusedMethodArgument: # No auto-correct for unused method arguments, but will still warn.
  AutoCorrect: false
Lint/UselessMethodDefinition:
  Enabled: true
