# --------------------
# Excluded Files
# --------------------
AllCops:
  Exclude:
    - "config/**/*"
    - "db/**/*"
    - "**/node_modules/**/*"
    - "**/spec/**/*"

# --------------------
# Metrics Cops
# --------------------
Metrics/AbcSize:
  Enabled: true
  Max: 35
Metrics/MethodLength:
  Enabled: true
  Max: 5
Metrics/ClassLength:
  Enabled: true
  Max: 200
Metrics/BlockLength:
  Exclude:
    - "**/concerns/**/*.rb"
    - "**/*.rake"
    - "**/api/api/**/*.rb" # we exclude grape because we wrap calls in large blocks. No easy way to shrink

# --------------------
# Layout Cops
# --------------------
Layout/LineLength:
  Enabled: true
  Max: 120
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/AccessModifierIndentation: # private/protected/public
  EnforcedStyle: outdent
Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: no_empty_lines
Layout/FirstHashElementIndentation: # Causing all sorts of unexpected results. Buggy as
  Enabled: false
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: false

# --------------------
# Style Cops
# --------------------
Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses
Style/Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/CombinableLoops:
  Enabled: true
Style/KeywordParametersOrder:
  Enabled: true
Style/RedundantSelfAssignment:
  Enabled: true
Style/SoleNestedConditional:
  Enabled: true
Style/HashSyntax:
  Enabled: false
Style/AccessorGrouping:
  Enabled: false
Style/ArrayCoercion:
  Enabled: false
Style/BisectedAttrAccessor:
  Enabled: false
Style/CaseLikeIf:
  Enabled: false
Style/ExplicitBlockArgument:
  Enabled: false
Style/ExponentialNotation:
  Enabled: false
Style/GlobalStdStream:
  Enabled: false
Style/HashAsLastArrayItem:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashLikeCase:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/OptionalBooleanParameter:
  Enabled: false
Style/RedundantAssignment:
  Enabled: false
Style/RedundantFetchBlock:
  Enabled: false
Style/RedundantFileExtensionInRequire:
  Enabled: false
Style/RedundantRegexpCharacterClass:
  Enabled: false
Style/RedundantRegexpEscape:
  Enabled: false
Style/SingleArgumentDig:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false
Style/StringConcatenation:
  Enabled: false
Style/ClassAndModuleChildren:
  Exclude:
    - "**/api/api/**/*.rb"
Style/ClassVars:
  Exclude:
    - "**/api/api/**/*.rb"

# --------------------
# Lint Cops
# --------------------
Lint/DuplicateRequire:
  Enabled: true
Lint/EmptyFile:
  Enabled: true
Lint/TrailingCommaInAttributeDeclaration:
  Enabled: true
Lint/UselessMethodDefinition:
  Enabled: true
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: false
Lint/DeprecatedOpenSSLConstant:
  Enabled: false
Lint/DuplicateElsifCondition:
  Enabled: false
Lint/DuplicateRescueException:
  Enabled: false
Lint/EmptyConditionalBody:
  Enabled: false
Lint/FloatComparison:
  Enabled: false
Lint/MissingSuper:
  Enabled: false
Lint/MixedRegexpCaptureTypes:
  Enabled: false
Lint/OutOfRangeRegexpRef:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/SelfAssignment:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Lint/TopLevelReturnWithArgument:
  Enabled: false
Lint/UnreachableLoop:
  Enabled: false
