require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec

inherit_from:
  - .rubocop-sentia.yml
  # - .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    # - app/admin/**/*
    # - app/channels/**/*
    # - app/jobs/**/*
    - bin/**/*
    - config/**/*
    - db/migrate/**/*
    - db/schema.rb
    # - script/**/*
    - node_modules/**/*
    # - Gemfile
    - Rakefile
    # - config.ru
